# -*- coding: utf-8 -*-
"""RGB_Dishes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z8cPFv4D9UPRhOtV4qCbSnMNip59gipl
"""

from google.cloud import storage
import os

client = storage.Client.create_anonymous_client()
bucket = client.bucket('nutrition5k_dataset')

# Adjust prefix based on the folder structure
blobs = bucket.list_blobs(prefix='nutrition5k_dataset/imagery/realsense_overhead/')

count = 0
for blob in blobs:
    if count >= 1000: break

    # We only want the RGB files
    if blob.name.endswith('rgb.png'):
        filename = os.path.join("my_images", blob.name.split('/')[-2] + ".png")
        os.makedirs(os.path.dirname(filename), exist_ok=True)
        blob.download_to_filename(filename)
        count += 1
        print(f"Downloaded {count}/1000")

import pandas as pd
import os
import json
from google.colab import auth

# 1. Authenticate your session
print("Step 1: Authenticating Google Cloud session...")
auth.authenticate_user()

# 2. Download the metadata files using the modern gcloud storage CLI
print("\nStep 2: Downloading metadata from GCS...")
# We download both cafe1 and cafe2 to ensure we find all 1,000 dish IDs
!gcloud storage cp gs://nutrition5k_dataset/nutrition5k_dataset/metadata/dish_metadata_cafe1.csv .
!gcloud storage cp gs://nutrition5k_dataset/nutrition5k_dataset/metadata/dish_metadata_cafe2.csv .

# 3. Identify your downloaded images
print("\nStep 3: Indexing local images...")
image_folder = 'my_images' # Ensure this matches your folder name
downloaded_ids = [os.path.splitext(f)[0] for f in os.listdir(image_folder) if f.endswith(('.png', '.jpg'))]
print(f"Found {len(downloaded_ids)} images in /{image_folder}")

# 4. Merge and Filter Metadata
print("\nStep 4: Processing metadata and matching IDs...")
# Load both CSVs and combine them
cols = ['dish_id', 'calories', 'mass', 'fat', 'carb', 'protein']
df1 = pd.read_csv('dish_metadata_cafe1.csv', header=None, usecols=[0,1,2,3,4,5], names=cols)
df2 = pd.read_csv('dish_metadata_cafe2.csv', header=None, usecols=[0,1,2,3,4,5], names=cols)

full_metadata = pd.concat([df1, df2]).drop_duplicates(subset='dish_id')

# Filter for only the 1,000 images you have
filtered_metadata = full_metadata[full_metadata['dish_id'].isin(downloaded_ids)]

# 5. Export to JSON
print("\nStep 5: Exporting to JSON...")
nutrition_dict = filtered_metadata.set_index('dish_id').to_dict(orient='index')

with open('nutrition_labels_1000.json', 'w') as f:
    json.dump(nutrition_dict, f, indent=4)

print("-" * 30)
print(f"DONE! Created 'nutrition_labels_1000.json'")
print(f"Matched {len(nutrition_dict)} out of {len(downloaded_ids)} images.")
print("-" * 30)

!zip -r my_images_1000.zip my_images/

import zipfile
import os

zip_file_path = 'my_images_1000.zip'
image_count = 0

with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    for file_info in zip_ref.infolist():
        # Check if it's a file and not a directory, and if it's a PNG image
        if not file_info.is_dir() and file_info.filename.endswith('.png'):
            image_count += 1

print(f"The zip file '{zip_file_path}' contains {image_count} PNG images.")

if image_count == 1000:
    print("Verification successful: The zip file contains exactly 1000 PNG images.")
else:
    print("Verification failed: The zip file does NOT contain 1000 PNG images.")